DAT-66319 [Tm2] client's buffer is getting full and cause events to be lost and orphans
datorama/Timbermill pull request #36
Opened 2020-08-26 16:33 UTC by oz-zafar

2020-08-27 07:50 UTC, oz-zafar commented on timbermill-client/src/main/java/com/datorama/oss/timbermill/pipe/TimbermillClient.java
>              try {
I noticed we don't close executorService in ElasticsearchClient,
so not sure if it's missing there or it's redundant here

2020-08-27 08:00 UTC, DvirKatz commented on timbermill-client/src/main/java/com/datorama/oss/timbermill/pipe/TimbermillClient.java
> +        Runnable getAndSendEventsTask = () -> {
extract to a method if possible

2020-08-27 13:39 UTC, edengal requested changes

2020-08-27 13:39 UTC, edengal commented on timbermill-client/src/main/java/com/datorama/oss/timbermill/pipe/TimbermillClient.java
>  import java.net.MalformedURLException;
On second thought, don't change name, it will break customers using it

2020-08-27 13:39 UTC, edengal commented on timbermill-client/src/main/java/com/datorama/oss/timbermill/pipe/TimbermillClient.java
> +            LOG.info("starting send events thread");
Capital - Starting

2020-08-30 10:29 UTC, edengal approved these changes

2020-08-30 10:29 UTC, merged