Add python client
datorama/Timbermill pull request #51
Opened 2020-10-22 12:48 UTC by shimk52

2020-10-25 11:27 UTC, aperfectpoint requested changes
@shimk52 I don't think we need to move every down to Java, let's just add a `python` directory (notice the lower-case).
@edengal - maybe we'll put all the clients under `timbermill-client`?

2020-10-25 11:27 UTC, aperfectpoint commented on Python/setup.py
> +    author_email="shimonkle@gmail.com",
put your salesforce email

2020-10-25 12:28 UTC, shimk52 commented
@aperfectpoint I'm fine with both
The `Java` directory was per @edengal's request

2020-10-25 15:17 UTC, edengal commented
@aperfectpoint the root folder is currently a maven root dir with a pom file, doesn't make sense to add another completely different project under the same path as the root to the maven project, same goes for the client, I rather we not mixed those.

2020-10-25 15:20 UTC, edengal commented
@shimk52 Can you please change the dirs name to `timbermill-java` `timbermill-python`

2020-10-25 15:46 UTC, shimk52 commented
@edengal Done

2020-10-26 08:22 UTC, aperfectpoint approved these changes

2020-10-26 08:55 UTC, edengal approved these changes

2020-10-26 08:57 UTC, merged